# Generated by Django 2.0.2 on 2019-04-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadro_clinico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadroclinico',
            name='fuma_frequencia',
            field=models.CharField(blank=True, choices=[('nunca', 'nunca'), ('raramente', 'raramente'), ('normalmente', 'normalmente'), ('frequentemente', 'frequentemente'), ('sempre', 'sempre')], max_length=120, null=True),
        ),
    ]
