# Generated by Django 2.0.2 on 2019-04-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadro_clinico', '0002_auto_20190405_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadroclinico',
            name='bebe_frequencia',
            field=models.CharField(blank=True, choices=[('nunca', 'nunca'), ('raramente', 'raramente'), ('normalmente', 'normalmente'), ('frequentemente', 'frequentemente'), ('sempre', 'sempre')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='quadroclinico',
            name='pratica_frequencia',
            field=models.CharField(blank=True, choices=[('nunca', 'nunca'), ('raramente', 'raramente'), ('normalmente', 'normalmente'), ('frequentemente', 'frequentemente'), ('sempre', 'sempre')], max_length=120, null=True),
        ),
    ]
