# Generated by Django 2.1.7 on 2019-03-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=1)),
                ('tipoSanguineo', models.CharField(max_length=3)),
                ('dataNasc', models.DateTimeField()),
            ],
        ),
    ]
