insert into medical_speciality values 
(1,"Allergy/Immunology"),
(2,"Ambulance Service Supplier"),
(3,"Ambulatory Surgical Center"),
(4,"Anesthesiologist Assistants"),
(5,"Anesthesiology"),
(6,"Audiologist (billing independently)"),
(7,"CRNA"),
(8,"Cardiac Electrophysiology"),
(9,"Cardiac Surgery"),
(10,"Cardiology"),
(11,"Certified Clinical Nurse Specialist"),
(12,"Certified Nurse Midwife"),
(13,"Chiropractic"),
(14,"Clinical Laboratory"),
(15,"Clinical Psychologist"),
(16,"Colorectal Surgery (formerly proctology)"),
(17,"Critical Care (Intensivists)"),
(18,"Dermatology"),
(19,"Diagnostic Radiology"),
(20,"Emergency Medicine"),
(21,"Endocrinology"),
(22,"Family Practice"),
(23,"Gastroenterology"),
(24,"General Practice"),
(25,"General Surgery"),
(26,"Geriatric Medicine"),
(27,"Geriatric Psychiatry"),
(28,"Gynecological/Oncology"),
(29,"Hand Surgery"),
(30,"Hematology"),
(31,"Hematology Oncology"),
(32,"Hospice and Palliative Care"),
(33,"Independent Diagnostic Testing Facility"),
(34,"Infectious Disease"),
(35,"Internal Medicine"),
(36,"Interventional Pain Management"),
(37,"Interventional Radiology"),
(38,"Licensed Clinical Social Worker"),
(39,"Mammographic Screening Center"),
(40,"Mass Immunization Roster Biller"),
(41,"Maxillofacial Surgery"),
(42,"Medical Oncology"),
(43,"Multispecialty Clinic/Group Practice"),
(44,"Nephrology"),
(45,"Neurology"),
(46,"Neuropsychiatry"),
(47,"Neurosurgery"),
(48,"Nuclear Medicine"),
(49,"Nurse Practitioner"),
(50,"Obstetrics/Gynecology"),
(51,"Occupational therapist"),
(52,"Ophthalmology"),
(53,"Optometry"),
(54,"Oral Surgery (dentists only)"),
(55,"Orthopedic Surgery"),
(56,"Osteopathic Manipulative Medicine"),
(57,"Otolaryngology"),
(58,"Pain Management"),
(59,"Pathology"),
(60,"Pediatric Medicine"),
(61,"Peripheral Vascular Disease"),
(62,"Pharmacy"),
(63,"Physical Medicine and Rehabilitation"),
(64,"Physical Therapist"),
(65,"Physician Assistant"),
(66,"Plastic and Reconstructive Surgery"),
(67,"Podiatry"),
(68,"Portable X-ray"),
(69,"Preventive Medicine"),
(70,"Psychiatry"),
(71,"Psychologist (billing independently)"),
(72,"Public Health Welfare Agency"),
(73,"Pulmonary Disease"),
(74,"Radiation Oncology"),
(75,"Radiation Therapy"),
(76,"Registered Dietician/Nutrition Professional"),
(77,"Rheumatology"),
(78,"Sleep Medicine"),
(79,"Slide Preparation Facility"),
(80,"Speech Language Pathologist"),
(81,"Sports Medicine"),
(82,"Surgical Oncology"),
(83,"Thoracic Surgery"),
(84,"Urology"),
(85,"Vascular Surgery")
;


