-- MySQL Script generated by MySQL Workbench
-- Fri Apr  5 15:43:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Time Scrum 3

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stagiop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stagiop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stagiop` DEFAULT CHARACTER SET utf8 ;
USE `stagiop` ;

-- -----------------------------------------------------
-- Table `stagiop`.`SITUACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stagiop`.`SITUACAO` (
  `SIT_ID` INT NOT NULL AUTO_INCREMENT,
  `SIT_DESC` VARCHAR(45) NULL,
  `SIT_Vagas` VARCHAR(45) NULL,
  `SIT_Medicos` VARCHAR(45) NULL,
  `SIT_Disp` VARCHAR(45) NULL COMMENT 'Este atributo tem como objetivo saber a disponibilidade do Hospital ou Ala',
  PRIMARY KEY (`SIT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stagiop`.`HOSPITAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stagiop`.`HOSPITAL` (
  `HSP_ID` INT NOT NULL AUTO_INCREMENT,
  `CNPJ` VARCHAR(20) NULL,
  `NOME` VARCHAR(100) NULL,
  `ENDERECO` VARCHAR(200) NULL,
  `TELEFONE` INT NULL,
  `SIT_ID` INT NULL,
  PRIMARY KEY (`HSP_ID`),
  INDEX `fk_HOSPITAL_SITUACAO_idx` (`SIT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_HOSPITAL_SITUACAO`
    FOREIGN KEY (`SIT_ID`)
    REFERENCES `stagiop`.`SITUACAO` (`SIT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stagiop`.`ESPECIALIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stagiop`.`ESPECIALIDADE` (
  `ESP_ID` INT NOT NULL AUTO_INCREMENT,
  `ESP_DESC` VARCHAR(45) NULL,
  PRIMARY KEY (`ESP_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stagiop`.`ALA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stagiop`.`ALA` (
  `ALA_ID` INT NOT NULL AUTO_INCREMENT,
  `HSP_ID` INT NOT NULL,
  `SIT_ID` INT NOT NULL,
  `ESP_ID` INT NOT NULL,
  `ALA_Tipo` VARCHAR(45) NULL COMMENT '# Tipo de Ala:\n\nAmbulatório\nEnfermaria\nEspecial',
  PRIMARY KEY (`ALA_ID`),
  INDEX `fk_ALA_HOSPITAL1_idx` (`HSP_ID` ASC) VISIBLE,
  INDEX `fk_ALA_SITUACAO1_idx` (`SIT_ID` ASC) VISIBLE,
  INDEX `fk_ALA_ESPECIALIDADE1_idx` (`ESP_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ALA_HOSPITAL1`
    FOREIGN KEY (`HSP_ID`)
    REFERENCES `stagiop`.`HOSPITAL` (`HSP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALA_SITUACAO1`
    FOREIGN KEY (`SIT_ID`)
    REFERENCES `stagiop`.`SITUACAO` (`SIT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALA_ESPECIALIDADE1`
    FOREIGN KEY (`ESP_ID`)
    REFERENCES `stagiop`.`ESPECIALIDADE` (`ESP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stagiop`.`PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stagiop`.`PACIENTE` (
  `PAC_ID` INT NOT NULL AUTO_INCREMENT,
  `PAC_NOME` VARCHAR(45) NULL,
  `PAC_IDADE` INT NULL,
  `PAC_GENERO` VARCHAR(45) NULL,
  PRIMARY KEY (`PAC_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stagiop`.`LEITO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stagiop`.`LEITO` (
  `LEI_ID` INT NOT NULL AUTO_INCREMENT,
  `ALA_ID` INT NOT NULL,
  `PAC_ID` INT NULL,
  `LEI` VARCHAR(45) NULL,
  PRIMARY KEY (`LEI_ID`),
  INDEX `fk_LEITO_ALA1_idx` (`ALA_ID` ASC) VISIBLE,
  INDEX `fk_LEITO_PACIENTE1_idx` (`PAC_ID` ASC) VISIBLE,
  CONSTRAINT `fk_LEITO_ALA10`
    FOREIGN KEY (`ALA_ID`)
    REFERENCES `stagiop`.`ALA` (`ALA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LEITO_PACIENTE10`
    FOREIGN KEY (`PAC_ID`)
    REFERENCES `stagiop`.`PACIENTE` (`PAC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stagiop`.`LEITO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stagiop`.`LEITO` (
  `LEI_ID` INT NOT NULL AUTO_INCREMENT,
  `ALA_ID` INT NOT NULL,
  `PAC_ID` INT NULL,
  `LEI` VARCHAR(45) NULL,
  PRIMARY KEY (`LEI_ID`),
  INDEX `fk_LEITO_ALA1_idx` (`ALA_ID` ASC) VISIBLE,
  INDEX `fk_LEITO_PACIENTE1_idx` (`PAC_ID` ASC) VISIBLE,
  CONSTRAINT `fk_LEITO_ALA10`
    FOREIGN KEY (`ALA_ID`)
    REFERENCES `stagiop`.`ALA` (`ALA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LEITO_PACIENTE10`
    FOREIGN KEY (`PAC_ID`)
    REFERENCES `stagiop`.`PACIENTE` (`PAC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
