-- MySQL Script generated by MySQL Workbench
-- qua 08 mai 2019 00:47:25 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kiizj5q0n6quilvc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kiizj5q0n6quilvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kiizj5q0n6quilvc` DEFAULT CHARACTER SET utf8 ;
USE `kiizj5q0n6quilvc` ;

-- -----------------------------------------------------
-- Table `kiizj5q0n6quilvc`.`SITUATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kiizj5q0n6quilvc`.`SITUATION` (
  `SIT_ID` INT NOT NULL AUTO_INCREMENT,
  `SIT_DESC` VARCHAR(45) NULL,
  `SIT_Vagas` VARCHAR(45) NULL,
  `SIT_Medicos` VARCHAR(45) NULL,
  `SIT_Disp` VARCHAR(45) NULL COMMENT 'Este atributo tem como objetivo saber a disponibilidade do Hospital ou Ala',
  PRIMARY KEY (`SIT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kiizj5q0n6quilvc`.`HOSPITAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kiizj5q0n6quilvc`.`HOSPITAL` (
  `HSP_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `HSP_CNPJ` VARCHAR(20) NOT NULL COMMENT 'Campo de CNPJ',
  `HSP_NAME` VARCHAR(100) NOT NULL COMMENT 'Nome do Hospital',
  `HSP_ADDRESS` VARCHAR(200) NOT NULL COMMENT 'Endereço do Hospital',
  `HSP_TELEPHONE` VARCHAR(30) NOT NULL COMMENT 'Telefone do Hospital',
  `SIT_ID` INT NULL,
  `HSP_STATUS` VARCHAR(45) NULL COMMENT 'Status do Hospital',
  PRIMARY KEY (`HSP_ID`),
  INDEX `fk_HOSPITAL_SITUATION_idx` (`SIT_ID` ASC),
  UNIQUE INDEX `CNPJ_UNIQUE` (`HSP_CNPJ` ASC),
  CONSTRAINT `fk_HOSPITAL_SITUACAO`
    FOREIGN KEY (`SIT_ID`)
    REFERENCES `kiizj5q0n6quilvc`.`SITUATION` (`SIT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kiizj5q0n6quilvc`.`SPECIALITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kiizj5q0n6quilvc`.`SPECIALITY` (
  `SPC_ID` INT NOT NULL AUTO_INCREMENT,
  `SPC_DESC` VARCHAR(45) NULL COMMENT 'Descricao da Especialidade',
  PRIMARY KEY (`SPC_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kiizj5q0n6quilvc`.`WING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kiizj5q0n6quilvc`.`WING` (
  `WNG_ID` INT NOT NULL AUTO_INCREMENT,
  `HSP_ID` INT NOT NULL,
  `SIT_ID` INT NOT NULL,
  `SPC_ID` INT NOT NULL,
  `WNG_Tipo` VARCHAR(45) NULL COMMENT '# Tipo de Ala:\n\nAmbulatório\nEnfermaria\nEspecial',
  PRIMARY KEY (`WNG_ID`),
  INDEX `fk_WING_HOSPITAL1_idx` (`HSP_ID` ASC),
  INDEX `fk_WING_SITUATION1_idx` (`SIT_ID` ASC),
  INDEX `fk_WING_SPECIALITY1_idx` (`SPC_ID` ASC),
  CONSTRAINT `fk_ALA_HOSPITAL1`
    FOREIGN KEY (`HSP_ID`)
    REFERENCES `kiizj5q0n6quilvc`.`HOSPITAL` (`HSP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALA_SITUACAO1`
    FOREIGN KEY (`SIT_ID`)
    REFERENCES `kiizj5q0n6quilvc`.`SITUATION` (`SIT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALA_ESPECIALIDADE1`
    FOREIGN KEY (`SPC_ID`)
    REFERENCES `kiizj5q0n6quilvc`.`SPECIALITY` (`SPC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kiizj5q0n6quilvc`.`PATIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kiizj5q0n6quilvc`.`PATIENT` (
  `PAT_CPF` VARCHAR(11) NOT NULL,
  `PAT_NAME` VARCHAR(200) NULL COMMENT 'Nome do Paciente',
  `PAT_GENDER` VARCHAR(1) NULL COMMENT 'Data de Nascimento',
  `PAT_BLOOD_TYPE` VARCHAR(1) NULL COMMENT 'Genero/Sexo do Paciente',
  `PAT_BIRTHDATE` DATE NULL COMMENT 'Cidade do Paciente',
  PRIMARY KEY (`PAT_CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kiizj5q0n6quilvc`.`BED`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kiizj5q0n6quilvc`.`BED` (
  `BED_ID` INT NOT NULL AUTO_INCREMENT,
  `WNG_ID` INT NOT NULL,
  `PAT_CPF` INT NULL,
  PRIMARY KEY (`BED_ID`),
  INDEX `fk_BED_WING1_idx` (`WNG_ID` ASC),
  INDEX `fk_BED_PATIENT1_idx` (`PAT_CPF` ASC),
  CONSTRAINT `fk_LEITO_ALA1`
    FOREIGN KEY (`WNG_ID`)
    REFERENCES `kiizj5q0n6quilvc`.`WING` (`WNG_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LEITO_PACIENTE1`
    FOREIGN KEY (`PAT_CPF`)
    REFERENCES `kiizj5q0n6quilvc`.`PATIENT` (`PAT_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
