-- MySQL Script generated by MySQL Workbench
-- Sun Mar 24 08:22:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema stagiop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stagiop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stagiop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `stagiop` ;

-- -----------------------------------------------------
-- Table `stagiop`.`bed_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagiop`.`bed_type` ;

CREATE TABLE IF NOT EXISTS `stagiop`.`bed_type` (
  `bdt_seq` INT(11) NOT NULL AUTO_INCREMENT,
  `bdt_desc` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`bdt_seq`),
  UNIQUE INDEX `bdt_UNIQUE` (`bdt_desc` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stagiop`.`hospital_situation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagiop`.`hospital_situation` ;

CREATE TABLE IF NOT EXISTS `stagiop`.`hospital_situation` (
  `stt_seq` INT(11) NOT NULL AUTO_INCREMENT,
  `stt_desc` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`stt_seq`),
  UNIQUE INDEX `stt_UNIQUE` (`stt_desc` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stagiop`.`hospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagiop`.`hospital` ;

CREATE TABLE IF NOT EXISTS `stagiop`.`hospital` (
  `hsp_seq` INT(11) NOT NULL AUTO_INCREMENT,
  `hsp_id` VARCHAR(14) NOT NULL COMMENT 'CNPJ do Hospital',
  `hsp_name` VARCHAR(200) NOT NULL,
  `hsp_address` VARCHAR(200) NOT NULL,
  `hsp_phone` VARCHAR(45) NOT NULL,
  `hsp_stt_seq` INT(11) NOT NULL DEFAULT '1' COMMENT 'Situação do Hospital. Default: 1 (To Be Defined)',
  PRIMARY KEY (`hsp_seq`),
  UNIQUE INDEX `hsp_UNIQUE` (`hsp_id` ASC) VISIBLE,
  INDEX `FK_hsp_stt_seq` (`hsp_stt_seq` ASC) VISIBLE,
  CONSTRAINT `FK_hsp_stt_seq`
    FOREIGN KEY (`hsp_stt_seq`)
    REFERENCES `stagiop`.`hospital_situation` (`stt_seq`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stagiop`.`bed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagiop`.`bed` ;

CREATE TABLE IF NOT EXISTS `stagiop`.`bed` (
  `bed_seq` INT(11) NOT NULL AUTO_INCREMENT,
  `bed_hsp_seq` INT(11) NOT NULL,
  `bed_bdt_seq` INT(11) NOT NULL,
  `bed_desc` VARCHAR(200) NOT NULL,
  `bed_available` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`bed_seq`),
  INDEX `FK_bed_hsp_seq` (`bed_hsp_seq` ASC) VISIBLE,
  INDEX `FK_bed_bdt_seq` (`bed_bdt_seq` ASC) VISIBLE,
  CONSTRAINT `FK_bed_bdt_seq`
    FOREIGN KEY (`bed_bdt_seq`)
    REFERENCES `stagiop`.`bed_type` (`bdt_seq`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_bed_hsp_seq`
    FOREIGN KEY (`bed_hsp_seq`)
    REFERENCES `stagiop`.`hospital` (`hsp_seq`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stagiop`.`hsp_doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagiop`.`hsp_doctor` ;

CREATE TABLE IF NOT EXISTS `stagiop`.`hsp_doctor` (
  `hdc_seq` INT(11) NOT NULL AUTO_INCREMENT,
  `hdc_hsp_seq` INT(11) NOT NULL,
  `hdc_id` VARCHAR(11) NOT NULL COMMENT 'CPF do Medico',
  PRIMARY KEY (`hdc_seq`),
  UNIQUE INDEX `hdc_UNIQUE` (`hdc_hsp_seq` ASC, `hdc_id` ASC) VISIBLE,
  CONSTRAINT `FK_hdc_hsp_seq`
    FOREIGN KEY (`hdc_hsp_seq`)
    REFERENCES `stagiop`.`hospital` (`hsp_seq`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stagiop`.`hsp_patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagiop`.`hsp_patient` ;

CREATE TABLE IF NOT EXISTS `stagiop`.`hsp_patient` (
  `hpt_seq` INT(11) NOT NULL AUTO_INCREMENT,
  `hpt_hsp_seq` INT(11) NOT NULL,
  `hpt_id` VARCHAR(200) NOT NULL,
  `hpt_bed_seq` INT(11) NULL DEFAULT NULL,
  `hpt_in_date` TIMESTAMP NOT NULL,
  `hpt_out_date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`hpt_seq`),
  UNIQUE INDEX `hpt_UNIQUE` (`hpt_hsp_seq` ASC, `hpt_id` ASC, `hpt_in_date` DESC) VISIBLE,
  INDEX `FK_hpt_bed_seq` (`hpt_bed_seq` ASC) VISIBLE,
  CONSTRAINT `FK_hpt_bed_seq`
    FOREIGN KEY (`hpt_bed_seq`)
    REFERENCES `stagiop`.`bed` (`bed_seq`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_hpt_hsp_seq`
    FOREIGN KEY (`hpt_hsp_seq`)
    REFERENCES `stagiop`.`hospital` (`hsp_seq`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stagiop`.`medical_speciality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagiop`.`medical_speciality` ;

CREATE TABLE IF NOT EXISTS `stagiop`.`medical_speciality` (
  `msp_seq` INT(11) NOT NULL AUTO_INCREMENT,
  `msp_desc` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`msp_seq`),
  UNIQUE INDEX `msp_UNIQUE` (`msp_desc` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stagiop`.`hsp_speciality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stagiop`.`hsp_speciality` ;

CREATE TABLE IF NOT EXISTS `stagiop`.`hsp_speciality` (
  `hms_hsp_seq` INT(11) NOT NULL,
  `hms_msp_seq` INT(11) NOT NULL,
  PRIMARY KEY (`hms_hsp_seq`, `hms_msp_seq`),
  INDEX `FK_hms_msp_seq` (`hms_msp_seq` ASC) VISIBLE,
  CONSTRAINT `FK_hms_hsp_seq`
    FOREIGN KEY (`hms_hsp_seq`)
    REFERENCES `stagiop`.`hospital` (`hsp_seq`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_hms_msp_seq`
    FOREIGN KEY (`hms_msp_seq`)
    REFERENCES `stagiop`.`medical_speciality` (`msp_seq`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

create user nodeuser@localhost identified by 'nodeuser@1234';
grant all privileges on stagiop.* to nodeuser@localhost;
ALTER USER 'nodeuser'@localhost IDENTIFIED WITH mysql_native_password BY 'nodeuser@1234';

FLUSH PRIVILEGES;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

