# Generated by Django 2.0.2 on 2019-04-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientetemalergia',
            name='alergia',
        ),
        migrations.RemoveField(
            model_name='pacientetemalergia',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='Alergia',
        ),
        migrations.DeleteModel(
            name='PacienteTemAlergia',
        ),
    ]
