# Generated by Django 2.0.2 on 2019-05-08 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraVacina',
            fields=[
                ('vac_idvaccine', models.AutoField(primary_key=True, serialize=False)),
                ('vac_name', models.CharField(max_length=30)),
                ('vac_date', models.DateField()),
                ('vac_next', models.DateField()),
                ('vac_batch', models.CharField(max_length=10)),
                ('vac_dose', models.IntegerField()),
                ('vac_responsible', models.CharField(max_length=30)),
                ('vac_cpfpatient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
            options={
                'db_table': 'vaccinationcard',
            },
        ),
    ]
