# Generated by Django 2.0.2 on 2019-05-11 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carteira_vacina', '0002_auto_20190511_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteiravacina',
            name='vac_medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteira_vacina.Medicamento'),
        ),
    ]
