# Generated by Django 2.0.2 on 2019-05-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira_vacina', '0003_auto_20190511_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='med_active_principle',
            field=models.CharField(max_length=500),
        ),
    ]
